### PR TITLE
Add HTTP status code field into APIError struct

### PR DESCRIPTION
**Pull request by srydai4hmt**
Hello.

Currently, if an error occurs in http get, http status code cannot be retrieved.
I submit this PR in order to get http status code.

Thanks.

### CODE REVIEW

**Review by bearmini — CHANGES_REQUESTED** [review]
Hi, thank you for this pull request!

The `ErrorCode` field in `APIError` is for Soracom specific 7 characters error code (e.g. `ABC1234`), this is used to know which component in Soracom platform returned the error and to identify what kind of error occurred by our engineers as described in https://developers.soracom.io/en/docs/tools/api-reference/

Existing SDK users may be using the field, so this pull request cannot be accepted as-is.

Alternatively, can you please modify this to add a field such as `HTTPStatusCode` into `APIError` struct and use it to avoid breaking change?

Thank you,

**Comment by moznion** [comment]
Thank you for your contribution 🙏

I suppose this should be our platform API issue. An API (e.g. `GetGroup` you pointed out in a test case) has to return an error code if the result was a failure, but some APIs didn't act like that.

Our team found the causes and has fixed a few APIs to return the error code correctly, so I deem maybe the changes in this pull-request are no longer needed.

Could you try it with the current API, @nigamishibumi?
And please feel free to ask us when you were faced something trouble.

**Comment by srydai4hmt** [comment]
@bearmini @moznion 
Thank you for your review :smile:
I’m going to add a HTTPStatusCode into APIError.

**Comment by srydai4hmt** [comment]
@bearmini @moznion

Fixed breaking changes.
Please check on that.

**Review by bearmini — APPROVED** [review]
:+1: 

Thank you for your contribution!

**Pull request merged**
